name: HTML validate
on:
  pull_request:
    paths:
      - 'index.html'
      - 'css/**'
      - '.github/workflows/html-validate.yml'
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  vnu:
    name: vnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@4ea5e57383ed7e14432ebbaae1b64893b7c5210b # v8.0.0
        with:
          root: .
